version: '3.8'

services:
  #Database
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'db'
    networks:
      - pgsite
  # pgAdmin
  # pg4:
  #   depends_on:
  #     - db
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: 'postgres@domain.com'
  #     PGADMIN_DEFAULT_PASSWORD: '1234'
  #   networks:
  #     - pgsite


networks:
  pgsite:

volumes:
  db_data: